#!/usr/bin/perl
use strict;
use warnings;
use XMLRPC::Lite;
use YAML;

my @ping = (
    'http://ping.feedburner.com/',
    'http://www.bloglines.com/ping',
    'http://rpc.technorati.jp/rpc/ping',
    'http://rpc.reader.livedoor.com/ping',
    'http://blogsearch.google.com/ping/RPC2',
);

my $blog_url  = shift || "http://blog.bulknews.net/mt/";
my $blog_name = shift || "blog.bulknews.net";

for my $ping (@ping) {
    warn "pinging $ping\n";
    my $result = XMLRPC::Lite->proxy($ping)->call("weblogUpdates.ping", $blog_name, $blog_url)->result;
    warn YAML::Dump $result;
}
