#!/usr/bin/perl
use strict;
use warnings;

use Module::CoreList;

my $mod = shift @ARGV or die "Usage: coremod Module\n";

my $ver = Module::CoreList->first_release($mod);
if ($ver) {
    my $mod_version = $Module::CoreList::version{$ver}{$mod} || '(undefined)';
    print "$mod is in core since perl $ver as $mod $mod_version\n";
} else {
    print "$mod is not in core\n";
}
