#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use Finance::Currency::Convert::Yahoo;
use Number::Format;

my $to   = "JPY";
GetOptions('--to=s', \$to);

no warnings 'uninitialized';
my $stuff = join ' ', @ARGV;
my($quant, $currency) = split /\s+/, $stuff;
if ($quant =~ /^\w{3}$/ && $currency =~ /^[\d\,\.]+$/) {
    ($quant, $currency) = ($currency, $quant);
}

if ($currency !~ /^\w{3}$/) {
    die "Unknown currency: $currency\n";
}

$quant =~ tr/,//d;

$currency = uc($currency);
$to       = uc($to);

my $how = Finance::Currency::Convert::Yahoo::convert($quant, $currency, $to) or exit;
print comma($quant), " $currency = ", comma($how), " $to\n";

sub comma {
    Number::Format->new->format_number($_[0]);
}
