#!/usr/bin/env ruby
require 'chronic'

class AtTask
  def initialize(*args)
    @date = Chronic.parse(args.join ' ')
    unless @date
      raise "Could not parse #{args.join ' '}"
    end
  end

  def run
    command = STDIN.read
    sec = (@date - Time.now).to_i
    pid = spawn 'bash', '-c', "sleep #{sec}; #{command}"
    puts "scheduled #{pid} on #{@date}"
  end
end

AtTask.new(*ARGV).run
