#!/usr/bin/env ruby
require 'chronic'
require 'open3'

class Task
  attr_accessor :time, :about
  def initialize(time, about)
    @time = Chronic.parse(time)
    @about = about
  end

  def queue
    sec = @time.to_i - Time.now.to_i
    system %Q[ssh #{ENV['HOME_MAC']} 'sleep #{sec} && ~/bin/pushme "#{about}" &']
  end
end

def parse(text)
  text.sub! /^me +/, ''
  if text.match /((?:in|on|at).*)(?:about|for|to)(.*)$/
    Task.new($1, $2.strip)
  else
    raise ArgumentError, "Couldn't parse text: say 'remind in 5 minutes about milk'"
  end
end

task = parse ARGV.join(' ')
task.queue
