#!/usr/bin/perl
use strict;
use warnings;
use DateTime;
use DateTime::TimeZone;

my @tz = (
    'UTC',
    'Pacific/Honolulu',
    'America/Los_Angeles',
    'America/Chicago',
    'America/New_York',
    'Europe/London',
    'Europe/Paris',
    'Europe/Berlin',
    'Europe/Rome',
    'Europe/Madrid',
    'Asia/Jakarta',
    'Asia/Bangkok',
    'Asia/Taipei',
    'Asia/Shanghai',
    'Asia/Hong_Kong',
    'Asia/Tokyo',
    'Australia/Sydney',
    'Pacific/Auckland',
);

my $now = DateTime->now;
for my $tz (@tz) {
    $now->set_time_zone($tz);
    my $date = $now->ymd('/') . ' ' . $now->hms(':');
    my $is_dst = $now->is_dst ? '*' : '';
    print "$date $tz$is_dst\n";
}

