#!/usr/bin/perl
use strict;
use warnings;
use DateTime;
use DateTime::TimeZone;

my @tz = (
    'UTC',
    'Pacific/Honolulu',
    'America/Los_Angeles',
    'America/Chicago',
    'America/New_York',
    'Europe/London',
    'Europe/Paris',
    'Europe/Berlin',
    'Europe/Rome',
    'Europe/Madrid',
    'Asia/Jakarta',
    'Asia/Bangkok',
    'Asia/Taipei',
    'Asia/Shanghai',
    'Asia/Hong_Kong',
    'Asia/Tokyo',
    'Australia/Sydney',
    'Pacific/Auckland',
);

my $dt = DateTime->now;
for my $tz (@tz) {
    $dt->set_time_zone($tz);
    print $dt->ymd('/'), ' ', $dt->hms(':'), " ", $tz, ($dt->is_dst ? '*' : ''), "\n";
}
